In [1]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

link = "https://en.wikipedia.org/wiki/List_of_Bollywood_films_of_2006"
source = urllib.request.urlopen(link).read()

soup = bs.BeautifulSoup(source,'lxml')



tables = soup.find_all('table',class_='wikitable')

len(tables)

3

In [2]:
#df1 = pd.read_html(str(tables[0]))[0]
#df2 = pd.read_html(str(tables[1]))[0]
#df3 = pd.read_html(str(tables[2]))[0]
#df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0] # avoided "ValueError: invalid literal for int() with base 10: '1"'

In [3]:
df3 = pd.read_html(str(tables[1]))[0]
 # avoided "ValueError: invalid literal for int() with base 10: '1"'
print(df3)

                           Title          Director  \
0                  36 China Town      Abbas-Mustan
1                  Aap Ki Khatir  Dharmesh Darshan
2                          Aatma     Deepak Ramsay
3                         Adharm               NaN
4                  Ahista Ahista               NaN
..                           ...               ...
101  Waris Shah: Ishq Daa Waaris        Manoj Punj
102                 Woh Lamhe...               NaN
103        Yun Hota Toh Kya Hota               NaN
104                        Zinda      Sanjay Gupta
105               Zindaggi Rocks    Tanuja Chandra

                                                  Cast  \
0    Kareena Kapoor, Shahid Kapoor, Akshaye Khanna,...
1    Sunil Shetty, Akshaye Khanna, Dino Morea, Amis...
2                                  Kapil Jhaveri, Neha
3                           Rahul Dev, Sonali Kulkarni
4                            Abhay Deol, Soha Ali Khan
..                                                 ...
101              Gurdas Mann, Juhi Chawla, Divya Dutta
102                       Shiney Ahuja, Kangana Ranaut
103     Ayesha Takia, Konkona Sen Sharma, Paresh Rawal
104  Sanjay Dutt, John Abraham, Lara Dutta, Celina ...
105                         Sushmita Sen, Shiney Ahuja

                       Genre  Sources
0          Thriller, Mystery      NaN
1    Comedy, Romance, Social      NaN
2                     Horror      NaN
3                        NaN      NaN
4             Drama, Romance      NaN
..                       ...      ...
101                      NaN      NaN
102   Drama, Romance, Social      NaN
103                    Drama      NaN
104                 Thriller      NaN
105                    Drama      NaN

[106 rows x 5 columns]

In [4]:
#df3.to_csv('film_2006.csv', header=False, index=False)

In [5]:
df3.isnull().sum()

Title         0
Director     54
Cast         16
Genre        29
Sources     106
dtype: int64

In [6]:
df3.head()

,Title,Director,Cast,Genre,Sources
0,36 China Town,Abbas-Mustan,"Kareena Kapoor, Shahid Kapoor, Akshaye Khanna,...","Thriller, Mystery",NaN
1,Aap Ki Khatir,Dharmesh Darshan,"Sunil Shetty, Akshaye Khanna, Dino Morea, Amis...","Comedy, Romance, Social",NaN
2,Aatma,Deepak Ramsay,"Kapil Jhaveri, Neha",Horror,NaN
3,Adharm,NaN,"Rahul Dev, Sonali Kulkarni",NaN,NaN
4,Ahista Ahista,NaN,"Abhay Deol, Soha Ali Khan","Drama, Romance",NaN

In [7]:
df3[df3['Director'].isnull()]

,Title,Director,Cast,Genre,Sources
3,Adharm,NaN,"Rahul Dev, Sonali Kulkarni",NaN,NaN
4,Ahista Ahista,NaN,"Abhay Deol, Soha Ali Khan","Drama, Romance",NaN
5,Aisa Kyon Hota Hai?,NaN,Rati Agnihotri,Drama,NaN
8,Anjaan,NaN,"Mahek Chahal, Vipul Gupta, Aamir Ali Malik",NaN,NaN
10,Anthony Kaun Hai?,NaN,"Sanjay Dutt, Arshad Warsi, Minissha Lamba, Anu...","Comedy, Thriller",NaN
15,Bas Ek Pal,NaN,"Juhi Chawla, Urmila Matondkar, Jimmy Sheirgill...",NaN,NaN
16,Being Cyrus,NaN,"Saif Ali Khan, Dimple Kapadia, Boman Irani, Na...","Drama, Comedy",NaN
18,Bhoot Unkle,NaN,Jackie Shroff,Comedy,NaN
19,Chand Ke Paar Chalo,NaN,"Preeti Jhangiani, Sanjay Narvekar",NaN,NaN
24,Darwaaza Bandh Rakho,NaN,"Aftab Shivdasani, Manisha Koirala","Comedy, Crime",NaN
25,Deadline: Sirf 24 Ghante,NaN,"Irrfan Khan, Konkona Sen Sharma",NaN,NaN
26,Devaki,NaN,"Ram Kapur, Perizaad Zorabian, Suman Ranganathan",Drama,NaN
31,Dor,NaN,"Ayesha Takia, Gul Panag, Shreyas Talpade","Drama, Social",NaN
32,Dulha Babu,NaN,NaN,NaN,NaN
33,Eight: The Power of Shani,NaN,"Raj Tara, Gulshan Grover",NaN,NaN
34,Ek Main Ek Tum,NaN,NaN,NaN,NaN
35,Family,NaN,"Amitabh Bachchan, Akshay Kumar, Bhumika Chawla","Drama, Thriller",NaN
38,Gangster,NaN,"Emraan Hashmi, Kangana Ranaut, Shiney Ahuja","Drama, Romance, Thriller, Musical",NaN
43,Humko Tumse Pyaar Hai,NaN,"Bobby Deol, Amisha Patel, Arjun Rampal","Drama, Romance",NaN
45,I See You,NaN,"Arjun Rampal, Vipasha Agarwal, Sonali Kulkarni...","Drama, Romance, Social",NaN
46,Jaane Hoga Kya,NaN,"Aftab Shivdasani, Bipasha Basu, Preeti Jhangia...","Supensene, Thriller, Sci-fi",NaN
47,Jaadu Sa Chal Gaya,NaN,NaN,NaN,NaN
48,Jaana - Let's Fall In Love,NaN,"Rajesh Khanna, Zeenat Aman",NaN,NaN
50,Jawani Diwani,NaN,"Emraan Hashmi, Hrishita Bhatt, Celina Jaitley,...","Comedy, Adult",NaN
54,Khosla Ka Ghosla,NaN,"Anupam Kher, Boman Irani",Comedy,NaN
55,Krishna,NaN,"Sonu Nigam, Sunidhi Chauhan",NaN,NaN
58,Lady Chatterjee - Sawan Dutta,NaN,NaN,NaN,NaN
61,Madhubaala,NaN,NaN,NaN,NaN
62,Malamaal Weekly,NaN,"Paresh Rawal, Om Puri, Ritesh Deshmukh, Reema ...",Comedy,NaN
64,Meri Jung,NaN,NaN,NaN,NaN
65,Mirza Sahiba,NaN,NaN,NaN,NaN
66,Mobile Phone,NaN,NaN,NaN,NaN
67,Mr 100% - The Real Player,NaN,NaN,NaN,NaN
68,Naksha,NaN,"Sunny Deol, Vivek Oberoi, Sameera Reddy, Jacki...","Thriller, Fantasy",NaN
71,Prateeksha,NaN,"Jimmy Sheirgill, Dia Mirza",NaN,NaN
73,Pyare Mohan,NaN,"Vivek Oberoi, Fardeen Khan, Esha Deol, Amrita ...",Comedy,NaN
74,Rafta Rafta,NaN,NaN,NaN,NaN
76,Rehguzar - The Road to Destiny,NaN,NaN,NaN,NaN
77,Rocky,NaN,"Zayed Khan, Minissha Lamba, Isha Sharvani","Action, Romance",NaN
79,Sacred Evil – A True Story,NaN,Sarika,"Horror, Thriller",NaN
80,Salaam Bacche,NaN,NaN,NaN,NaN
85,Shikhar,NaN,"Ajay Devgan, Bipasha Basu, Shahid Kapoor, Amri...",Drama,NaN
86,Shiva,NaN,Nisha Kothari,NaN,NaN
87,Souten: The Other Woman,NaN,"Gulshan Grover, Mahima Chaudhry",Drama,NaN
88,Strings - Bound By Faith,NaN,NaN,NaN,NaN
89,Sun Zara,NaN,NaN,NaN,NaN
91,Taxi No. 9211,NaN,"John Abraham, Nana Patekar, Sameera Reddy, Son...","Social, Thriller",NaN
92,Teesri Aankh: The Hidden Camera,NaN,"Sunny Deol, Amisha Patel, Neha Dhupia","Action, Thriller",NaN
93,The Killer,NaN,"Irrfan Khan, Emraan Hashmi, Nisha Kothari",NaN,NaN
96,Umar,NaN,NaN,NaN,NaN
98,Unns...Means Love,NaN,NaN,NaN,NaN
99,Utthaan,NaN,"Priyanshu Chatterjee, Neha Dhupia",NaN,NaN
102,Woh Lamhe...,NaN,"Shiney Ahuja, Kangana Ranaut","Drama, Romance, Social",NaN
103,Yun Hota Toh Kya Hota,NaN,"Ayesha Takia, Konkona Sen Sharma, Paresh Rawal",Drama,NaN

In [8]:
import imdb

moviesDB = imdb.IMDb()

# # Help?
# print(dir(moviesDB))
# ----------------------------------------
# 1) Search for a title
movies = moviesDB.search_movie('inception')

# print('Searching for "inception":')
# for movie in movies:
#     title = movie['title']
#     year = movie['year']
#     print(f'{title} - {year}')

## Help?
#print(movies[0].keys())

In [9]:
#getting director for 2020 movies using imdb API
def get_genre(x):
  genres = []
  try:
        movies = moviesDB.search_movie(x)
        id = movies[0].getID()
        movie = moviesDB.get_movie(id) 
        directors = movie['directors'] 
        direcStr = ' '.join(map(str,directors))
        genres.append(direcStr)
        return genres
  except:
    print("An exception occurred")

In [10]:
df3['director'] = df3['Title'].map(lambda x: get_genre(str(x)))

An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred

In [11]:
df3.isnull().sum()

Title         0
Director     54
Cast         16
Genre        29
Sources     106
director      9
dtype: int64

In [12]:
def get_genre(x):
  genres = []
  try:
        movies = moviesDB.search_movie(x)
        id = movies[0].getID()
        movie = moviesDB.get_movie(id) 
        genres = movie['genres'] 
        direcStr= ' '.join(map(str,genres))
        genres.append(direcStr)
        return genres
  except:
    print("An exception occurred")

In [13]:
df3['genre'] = df3['Title'].map(lambda x: get_genre(str(x)))

2020-09-09 13:40:25,528 CRITICAL [imdbpy] /opt/anaconda3/lib/python3.8/site-packages/imdb/_exceptions.py:33: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0880464/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode
    content = response.read()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 461, in read
    return self._readall_chunked()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 568, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 511, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
2020-09-09 13:40:25,541 CRITICAL [imdbpy] /opt/anaconda3/lib/python3.8/site-packages/imdb/__init__.py:734: caught an exception retrieving or parsing "main" info set for mopID "0880464" (accessSystem: http)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode
    content = response.read()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 461, in read
    return self._readall_chunked()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 568, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 511, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/__init__.py", line 732, in update
    ret = method(mopID)
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 439, in get_movie_main
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'reference')
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 376, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 247, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0880464/reference', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')}

An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred

2020-09-09 13:45:04,798 CRITICAL [imdbpy] /opt/anaconda3/lib/python3.8/site-packages/imdb/_exceptions.py:33: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find?q=Strings+-+Bound+By+Faith&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode
    content = response.read()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 461, in read
    return self._readall_chunked()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 568, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/anaconda3/lib/python3.8/http/client.py", line 511, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

An exception occurred
An exception occurred

In [14]:
df3.isnull().sum()

Title         0
Director     54
Cast         16
Genre        29
Sources     106
director      9
genre         7
dtype: int64

In [15]:
''''def get_genre(x):
  genres = []
  try:
        movies = moviesDB.search_movie(x)
        id = movies[0].getID()
        movie = moviesDB.get_movie(id) 
        directors = movie['directors'] 
        direcStr = ' '.join(map(str,directors))
        genres.append(direcStr)
        return genres
  except:
    print("An exception occurred")
''''

SyntaxError: EOL while scanning string literal (<ipython-input-15-4a1f3e5301ec>, line 13)

In [ ]:
df3.drop(['Director','Genre','Sources'],axis=1,inplace=True)

In [ ]:
df3.head()

In [ ]:
df3.isnull().sum()

In [ ]:
df=df3[df3['director'].isnull()]

In [ ]:
import imdb
ia = imdb.IMDb()
def get_dir(x):
  movies = moviesDB.search_movie(x)
  code= movies[0].getID()
  movie = ia.get_movie(code)
  for director in movie['directors']:
        return director['name']
  
x='Alag'
get_dir(x)

In [ ]:
import imdb
ia = imdb.IMDb()
def get_genre(x):
  movies = moviesDB.search_movie(x)
  code= movies[0].getID()
  movie = ia.get_movie(code)
  for genre in movie['genres']:
    return genre
  
x='Chehraa'
get_genre(x)

In [ ]:
#df.iloc[7,2]=df.iloc[7,2].fillna(get_director(df3.iloc[0,1]))
df.iloc[22,2]=df.iloc[22,2].fillna(get_director(x))
df.iloc[34,2]=df.iloc[34,2].fillna(get_director(get_dir('x=df3.iloc[7,0]')))
df.iloc[35,2]=df.iloc[35,2].fillna(get_director(x))
df.iloc[58,2]=df.iloc[58,2].fillna(get_director(x))
df.iloc[67,2]=df.iloc[67,2].fillna(get_director(x))
df.iloc[76,2]=df.iloc[76,2].fillna(get_director(x))
df.iloc[79,2]=df.iloc[79,2].fillna(get_director(x))
df.iloc[98,2]=df.iloc[98,2].fillna(get_director(x))

In [ ]:
x=df3.iloc[7,0]
print(x)
y=get_dir('x')
df3.iloc[7,2]=df3.iloc[7,2].fillna('spike')

In [ ]:
df3[df3['director'].isnull()]

In [ ]:
x=df3.iloc[34,0]
get_dir('x')
df3.iloc[34,2]=df3.iloc[34,2].fillna(get_dir(x))

In [ ]:
df

In [ ]:
import imdb

moviesDB = imdb.IMDb()
def get_genre(x):
  genres = []
  try:
        movies = moviesDB.search_movie(x)
        id = movies[0].getID()
        movie = moviesDB.get_movie(id)  
        directors = movie['directors'] 
        direcStr = ' '.join(map(str,directors))
        genres.append(direcStr)
        return genres
  except:
    print("An exception occurred")

In [ ]:
df3['director'] = df3['Title'].map(lambda x: get_genre(str(x)))

In [ ]:
df3.isnull().sum()

In [ ]:
df3.dropna()

In [ ]:
cd /Users/pradeepvaddigadda/desktop

In [ ]:
df3.to_csv('cleanedfilm_2006.csv', header=True, index=True)

In [ ]:
df=df3

In [17]:
df3

,Title,Director,Cast,Genre,Sources,director,genre
0,36 China Town,Abbas-Mustan,"Kareena Kapoor, Shahid Kapoor, Akshaye Khanna,...","Thriller, Mystery",NaN,[Abbas Alibhai Burmawalla Mastan Alibhai Burma...,"[Comedy, Mystery, Thriller, Comedy Mystery Thr..."
1,Aap Ki Khatir,Dharmesh Darshan,"Sunil Shetty, Akshaye Khanna, Dino Morea, Amis...","Comedy, Romance, Social",NaN,[Dharmesh Darshan],"[Comedy, Romance, Comedy Romance]"
2,Aatma,Deepak Ramsay,"Kapil Jhaveri, Neha",Horror,NaN,[Suparn Verma],"[Drama, Horror, Thriller, Drama Horror Thriller]"
3,Adharm,NaN,"Rahul Dev, Sonali Kulkarni",NaN,NaN,[Aziz Sejawal],"[Action, Crime, Drama, Action Crime Drama]"
4,Ahista Ahista,NaN,"Abhay Deol, Soha Ali Khan","Drama, Romance",NaN,[Shivam Nair],"[Drama, Romance, Drama Romance]"
...,...,...,...,...,...,...,...
101,Waris Shah: Ishq Daa Waaris,Manoj Punj,"Gurdas Mann, Juhi Chawla, Divya Dutta",NaN,NaN,[Manoj Punj],"[Drama, History, Drama History]"
102,Woh Lamhe...,NaN,"Shiney Ahuja, Kangana Ranaut","Drama, Romance, Social",NaN,[Mohit Suri],"[Biography, Drama, Romance, Biography Drama Ro..."
103,Yun Hota Toh Kya Hota,NaN,"Ayesha Takia, Konkona Sen Sharma, Paresh Rawal",Drama,NaN,[Naseeruddin Shah],"[Drama, Drama]"
104,Zinda,Sanjay Gupta,"Sanjay Dutt, John Abraham, Lara Dutta, Celina ...",Thriller,NaN,[Sanjay Gupta],"[Action, Drama, Mystery, Thriller, Action Dram..."
105,Zindaggi Rocks,Tanuja Chandra,"Sushmita Sen, Shiney Ahuja",Drama,NaN,[Tanuja Chandra],"[Drama, Romance, Drama Romance]"